[avito]
url = "https://www.avito.ru/all/telefony?owner[]=private&params[110618]=469735&params[110680]=458500&params[121588][0]=2850686&params[121588][1]=2850687&params[121588][2]=2850688&params[121588][3]=2850685&pmin=10000&s=104"
api_url = "https://www.avito.ru/web/1/js/items?categoryId=84&context=H4sIAAAAAAAA_wEiAN3_YToxOntzOjg6ImZyb21QYWdlIjtzOjY6ImlubGluZSI7fX78KVUiAAAA&localPriority=0&locationId=107620&owner%5B0%5D=private&params%5B110618%5D=469735&params%5B110680%5D=458500&params%5B121588%5D%5B0%5D=2850686&params%5B121588%5D%5B1%5D=2850687&params%5B121588%5D%5B2%5D=2850688&params%5B121588%5D%5B3%5D=2850685&presentationType=serp&priceMin=10000&privateOnly=1&sort=date"
proxy_string = "bYa4kY:UB4uzPUM4dAh@mproxy.site:20085"
socks5_proxy = "bYa4kY:UB4uzPUM4dAh@bproxy.site:20085"
proxy_change_url = "https://aproxy.site/?proxy_key=62dc7172077f93790ab178bba372bdac"
cookies_api_key = "sk_live_N805lkXT1fdWMSe1wedMJDgx2nMq6wVlYSum9iAH6Wc"
cookie_pool_size = 5
cookie_unblock_pause = 60
ignore_promotion = true
seller_skip = ["re:premium"]
max_age = 300
notify_max_age = 0
pages = 1
pause_between_pages = 2
title_must_contain = ["iphone"]
title_skip = ["книга", "книг", "журнал", "комикс", "airpods", "чехол", "кабель", "зарядк", "пленк", "стекло", "камер", "динамик", "запчаст", "разбор"]
pause_general = 12
pause_max = 40
web_port = 8765
